name: continuous integration #Workflow name

on:
  push:
    branches: [ master ] #The workflow triggered when pushed to master

jobs:
  test_suite:
    runs-on: ubuntu-latest #The test-suite, runs on the latest ubuntu VM
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2 # Loads repository into VM 
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2 # Installs Python 3.8
        with:
          python-version: 3.8
      - name: Install dependencies
        # Install pip
        # Install dependencies in requirements.txt if file exists
        run: |
          python -m pip install --upgrade pip 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # - name: Run Backend Tests
      # # Change directory to src
      # # Run tests
      #   run: |
      #     python -m unittest discover tests/backend_tests